server:
  port: 8081
spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  h2:
    console.enabled: true
  datasource:
#    url: jdbc:h2:file:C:/sources/h2db/target/demo;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./target/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect